<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>AzureSearch.ImageServingExample</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Azure.Search.Documents" Version="12.1.0-beta.2" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.25.1" />
    <PackageReference Include="dotenv.net" Version="4.0.0" />
  </ItemGroup>

</Project>
